# Enums and handler status codes mirroring readstat.h (v1.1.9).

# Return codes for parse handlers. SKIP_VARIABLE is only valid from the
# variable handler; subsequent variables keep their original index values.
const READSTAT_HANDLER_OK = Cint(0)
const READSTAT_HANDLER_ABORT = Cint(1)
const READSTAT_HANDLER_SKIP_VARIABLE = Cint(2)

@enum ReadStatType::Cint begin
    READSTAT_TYPE_STRING = 0
    READSTAT_TYPE_INT8
    READSTAT_TYPE_INT16
    READSTAT_TYPE_INT32
    READSTAT_TYPE_FLOAT
    READSTAT_TYPE_DOUBLE
    READSTAT_TYPE_STRING_REF
end

@enum ReadStatTypeClass::Cint begin
    READSTAT_TYPE_CLASS_STRING = 0
    READSTAT_TYPE_CLASS_NUMERIC
end

@enum ReadStatMeasure::Cint begin
    READSTAT_MEASURE_UNKNOWN = 0
    READSTAT_MEASURE_NOMINAL
    READSTAT_MEASURE_ORDINAL
    READSTAT_MEASURE_SCALE
end

@enum ReadStatAlignment::Cint begin
    READSTAT_ALIGNMENT_UNKNOWN = 0
    READSTAT_ALIGNMENT_LEFT
    READSTAT_ALIGNMENT_CENTER
    READSTAT_ALIGNMENT_RIGHT
end

@enum ReadStatCompress::Cint begin
    READSTAT_COMPRESS_NONE = 0
    READSTAT_COMPRESS_ROWS
    READSTAT_COMPRESS_BINARY
end

@enum ReadStatEndian::Cint begin
    READSTAT_ENDIAN_NONE = 0
    READSTAT_ENDIAN_LITTLE
    READSTAT_ENDIAN_BIG
end

@enum ReadStatIOFlags::Cint begin
    READSTAT_SEEK_SET = 0
    READSTAT_SEEK_CUR
    READSTAT_SEEK_END
end

@enum ReadStatError::Cint begin
    READSTAT_OK = 0
    READSTAT_ERROR_OPEN
    READSTAT_ERROR_READ
    READSTAT_ERROR_MALLOC
    READSTAT_ERROR_USER_ABORT
    READSTAT_ERROR_PARSE
    READSTAT_ERROR_UNSUPPORTED_COMPRESSION
    READSTAT_ERROR_UNSUPPORTED_CHARSET
    READSTAT_ERROR_COLUMN_COUNT_MISMATCH
    READSTAT_ERROR_ROW_COUNT_MISMATCH
    READSTAT_ERROR_ROW_WIDTH_MISMATCH
    READSTAT_ERROR_BAD_FORMAT_STRING
    READSTAT_ERROR_VALUE_TYPE_MISMATCH
    READSTAT_ERROR_WRITE
    READSTAT_ERROR_WRITER_NOT_INITIALIZED
    READSTAT_ERROR_SEEK
    READSTAT_ERROR_CONVERT
    READSTAT_ERROR_CONVERT_BAD_STRING
    READSTAT_ERROR_CONVERT_SHORT_STRING
    READSTAT_ERROR_CONVERT_LONG_STRING
    READSTAT_ERROR_NUMERIC_VALUE_IS_OUT_OF_RANGE
    READSTAT_ERROR_TAGGED_VALUE_IS_OUT_OF_RANGE
    READSTAT_ERROR_STRING_VALUE_IS_TOO_LONG
    READSTAT_ERROR_TAGGED_VALUES_NOT_SUPPORTED
    READSTAT_ERROR_UNSUPPORTED_FILE_FORMAT_VERSION
    READSTAT_ERROR_NAME_BEGINS_WITH_ILLEGAL_CHARACTER
    READSTAT_ERROR_NAME_CONTAINS_ILLEGAL_CHARACTER
    READSTAT_ERROR_NAME_IS_RESERVED_WORD
    READSTAT_ERROR_NAME_IS_TOO_LONG
    READSTAT_ERROR_BAD_TIMESTAMP_STRING
    READSTAT_ERROR_BAD_FREQUENCY_WEIGHT
    READSTAT_ERROR_TOO_MANY_MISSING_VALUE_DEFINITIONS
    READSTAT_ERROR_NOTE_IS_TOO_LONG
    READSTAT_ERROR_STRING_REFS_NOT_SUPPORTED
    READSTAT_ERROR_STRING_REF_IS_REQUIRED
    READSTAT_ERROR_ROW_IS_TOO_WIDE_FOR_PAGE
    READSTAT_ERROR_TOO_FEW_COLUMNS
    READSTAT_ERROR_TOO_MANY_COLUMNS
    READSTAT_ERROR_NAME_IS_ZERO_LENGTH
    READSTAT_ERROR_BAD_TIMESTAMP_VALUE
end

function readstat_error_message(error_code::ReadStatError)
    unsafe_string(@ccall libreadstat.readstat_error_message(error_code::ReadStatError)::Ptr{Cchar})
end

export READSTAT_HANDLER_OK, READSTAT_HANDLER_ABORT, READSTAT_HANDLER_SKIP_VARIABLE,
    readstat_error_message

for enum_type in (ReadStatType, ReadStatTypeClass, ReadStatMeasure, ReadStatAlignment,
                  ReadStatCompress, ReadStatEndian, ReadStatIOFlags, ReadStatError)
    @eval export $(nameof(enum_type))
    for instance in instances(enum_type)
        @eval export $(Symbol(instance))
    end
end
